### ISSUE TITLE
sed -R is not working during diraction-batch-create.

### ISSUE THREAD

**Issue by moonrumble** [AdrieanKhisbe/diractions#16]
tested on cygwin, mac and debian.

sed: unknown option -- R
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space

**Comment by AdrieanKhisbe** [comment]
@moonrumble On what platform are you having this issue?

the `-R` option is only set when os is not Darwin.
https://github.com/AdrieanKhisbe/diractions/blame/master/diractions.plugin.zsh#L380

I added tests on travis, that runs on ubuntu, and there is not issue

**Comment by AdrieanKhisbe** [comment]
@moonrumble It should be working now.

If it persist after updating  `diraction`, feel free to reopen issue and comment with all details you can provide. (os, logs, etc)
