### ISSUE TITLE
Completion for `command /<Tab>` works differently from `command cd <Tab>`

### ISSUE THREAD

**Issue by astyagun** [AdrieanKhisbe/diractions#18]
Given:
```sh
astyagun-mbp% diraction ls
List of diractions:
code     -  ~/Code
astyagun-mbp% code ls | grep rails
docker-rails-development
```

This works:
```sh
astyagun-mbp% code cd rails<Tab>
->
astyagun-mbp% code cd docker-rails-development
```

But this doesn't:
```sh
astyagun-mbp% code /rails<Tab>
 -- no matches found --
```

**Comment by AdrieanKhisbe** [comment]
Good catch @astyagun !

Will be shipped in incoming https://github.com/AdrieanKhisbe/diractions/tree/new-feature-set PR&release :)

**Comment by AdrieanKhisbe** [comment]
Hello again @astyagun,

#23 just landed and I released [v0.17.0]

(https://github.com/AdrieanKhisbe/diractions/releases/tag/v0.17.0).
Please give a try and tell me if it works for you :)

**Comment by astyagun** [comment]
Not sure if it's fixed fully yet. Given:

```sh
~
❯ alias | grep code
cdc='code cd'
code='_diraction-dispatch "/Users/astyagun/Code"'

~
❯ diraction ls
List of diractions:
code     -  ~/Code

~
❯ code ls
Arduino                         docker-rails-development        robot                           user_admin
books_distributor               rails_app                       setup
```

`code /dev<Tab>` expands to `code /docker-rails-development/` as expected. Some other cases don't work as expected, though. `code /rails<Tab>` and `code /set<Tab>` produce `code /` (removing everything after `/`).

(It's not a problems for me, though, as I'm using the `cdc` alias and completion works well with it)

**Comment by AdrieanKhisbe** [comment]
It doesn't seems I can reproduce.
On my computer, having typed `here /rails` in a `here` diraction with same folders as you, I get the correct behavior.
```$ here /docker-rails-development/
>>> Matching "/tmp/here" Subdirs :
/docker-rails-development/  /rails_app/               `
```

-----
It seems like the path finding does not find anything, and then prefix got removed
https://github.com/AdrieanKhisbe/diractions/blob/master/__diraction-dispatch#L32-L41

I suspect there is some issue around `sed`.
@astyagun  Can you tell me what **os** you are using, and what version&flavor you have? :)
(`man sed|head;man sed|tail`)

**Comment by astyagun** [comment]
The OS is macOS 10.15.4 (19E287)

```sh
~
❯ man sed | head

SED(1)                    BSD General Commands Manual                   SED(1)

NAME
     sed -- stream editor

SYNOPSIS
     sed [-Ealn] command [file ...]
     sed [-Ealn] [-e command] [-f command_file] [-i extension] [file ...]


~
❯ man sed | tail
AUTHORS
     Diomidis D. Spinellis <dds@FreeBSD.org>

BUGS
     Multibyte characters containing a byte with value 0x5C (ASCII `\') may be
     incorrectly treated as line continuation characters in arguments to the
     ``a'', ``c'' and ``i'' commands.  Multibyte characters cannot be used as
     delimiters with the ``s'' and ``y'' commands.

BSD                              May 10, 2005                              BSD
```

**Comment by AdrieanKhisbe** [comment]
Thanks @astyagun :)

But damn, I was expecting a different answer about `sed` that could have sed some light 😁 

I'll try to have a look later.
In  the meantime, if you could provide me your `zsh --version` also :)

**Comment by astyagun** [comment]
```sh
❯ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

Zsh config can be found here: https://github.com/astyagun/.files/tree/45f41a110f559ece3a7a81dadfe3e151676825e0/zsh

**Comment by AdrieanKhisbe** [comment]
Thanks for those details, @astyagun :)

I had a deeper look, but nothing standed out. :confused:
sed is the same, didn't saw some specific glob/pattern config that could explain behavior.

Would you mind instrumenting `__diraction-dispatcher` to pinpoint what part behave differently? 🙂 

The following line is to be inserted [between line 38 and 39](https://github.com/AdrieanKhisbe/diractions/blob/master/__diraction-dispatch#L38-L39)
`echo "dirdir=$dirdir\nsubcommand=$subcommand\nnslash=$nslash\ndirpattern=$dirpattern\npattern=$pattern\ncmd=$cmd\nmatches=$matches\npaths=$paths\n" >> /tmp/debug.diraction.log`

**Comment by astyagun** [comment]
```plain
dirdir=/Users/astyagun/Code
subcommand=/rails
nslash=1
dirpattern=*/
pattern=/.*r.*.*a.*.*i.*.*l.*.*s.*
cmd=builtin cd /Users/astyagun/Code > /dev/null && ls -d -- */ 2>>/dev/null | sed -E 's:^:/:g' | grep "/.*r.*.*a.*.*i.*.*l.*.*s.*"
matches=/docker-rails-development/
/rails_app/
paths=/docker-rails-development/ /rails_app/

dirdir=/Users/astyagun/Code
subcommand=/set
nslash=1
dirpattern=*/
pattern=/.*s.*.*e.*.*t.*
cmd=builtin cd /Users/astyagun/Code > /dev/null && ls -d -- */ 2>>/dev/null | sed -E 's:^:/:g' | grep "/.*s.*.*e.*.*t.*"
matches=/docker-rails-development/
/setup/
paths=/docker-rails-development/ /setup/
```

**Comment by AdrieanKhisbe** [comment]
Thanks a lot :)

🤔  this is what is expected to be found, I have the same:

```bash
dirdir=/tmp/here
subcommand=/set
nslash=1
dirpattern=*/
pattern=/.*s.*.*e.*.*t.*
cmd=builtin cd /tmp/here > /dev/null && ls -d -- */ 2>>/dev/null | sed -E 's:^:/:g' | grep "/.*s.*.*e.*.*t.*"
matches=/docker-rails-development/
/setup/
paths=/docker-rails-development/ /setup/
```
Which means the issue might be related with the completion configuration.
I'll  have a second look to your dotfiles

**Comment by AdrieanKhisbe** [comment]
> I'll have a second look to your dotfiles 👀 

I might say, it might be related to **zinit**, which seems to have some specificities with 
how completion is handled (https://github.com/zdharma/zinit#completions / https://github.com/zdharma/zinit#completions-2)  and some issues/gotcha (https://github.com/zdharma/zinit/issues?q=is%3Aissue+completion) 

As a zinit user you might more easily makes sense of these leads than I could. 🤞 

Also maybe this line also can be part of this unexpected behavior https://github.com/astyagun/.files/blob/45f41a110f559ece3a7a81dadfe3e151676825e0/zsh/plugins.zsh#L50

**Comment by astyagun** [comment]
> Also maybe this line also can be part of this unexpected behavior https://github.com/astyagun/.files/blob/45f41a110f559ece3a7a81dadfe3e151676825e0/zsh/plugins.zsh#L50

This hack is a workaround of [this issue](https://github.com/zdharma/zinit/issues/139) AFAIR 🤔 I don't have deep understanding of how completions (in general and in zinit) work unfortunately.

But It's just my setup, that is affected by this, then. Good to know. I'll just continue using my `cdc` alias. 👍 

Thanks for investigating! 🙏

**Comment by AdrieanKhisbe** [comment]
Thanks @astyagun 🙂, I wish you good luck.

And if you others suggestions, you're more than welcome! =)
