### ISSUE TITLE
Add --create-missing-dir

### ISSUE THREAD

**Issue by NightMachinery** [AdrieanKhisbe/diractions#19]
Do a mkdir -p on missing stuff.

**Comment by AdrieanKhisbe** [comment]
Hey @NightMachinary 

Will be shipped soon in incoming https://github.com/AdrieanKhisbe/diractions/tree/new-feature-set PR&release :)

**Comment by AdrieanKhisbe** [comment]
Hello again @NightMachinary,
[v0.17.0](https://github.com/AdrieanKhisbe/diractions/releases/tag/v0.17.0) is out.

Hope this helps you out

**Comment by NightMachinery** [comment]
@AdrieanKhisbe Thanks ^_^ ❤️
